site_name: Global Economy Equilibrium Scenario Builder
copyright: "&copy; 2020â€“2022 Global Projection Model Network"

theme:
    name: material
    font: 
        code: "Ubuntu Mono"
        text: "Open Sans"
    icon: 
        logo: fontawesome/solid/infinity
        repo: fontawesome/brands/github
    favicon: "mkdocs/globe.ico"
    palette:
        scheme: default
    features:
        - navigation.tabs
        - navigation.indexes
        - navigation.top


repo_url: https://github.com/Global-Projection-Model-Network/GEES
repo_name: GEES on GitHub
edit_uri: ""

extra:
  version: 2022
  generator: false

use_directory_urls: false
docs_dir: ./docs-source
site_dir: ./docs

extra_javascript:
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - mkdocs/extra.css

markdown_extensions:
    pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
    pymdownx.critic: {}
    pymdownx.highlight: {}
    pymdownx.superfences: {}
    admonition: {}
    pymdownx.details: {}
    footnotes: {}
    meta: {}
    pymdownx.arithmatex:
      generic: true
    attr_list: {}
    pymdownx.snippets: {"base_path": [".", "./docs-source"]}
    md_in_html: {}
    pymdownx.tabbed:
      alternate_style: true


plugins:
  - search
  - awesome-pages

